// src/components/data-bound/layouts/list.vue
<script lang="ts" setup>
import type { Context } from '../services/context';
import type { ComponentContext, ListConfig } from '../services/types';
import Multi from '../containers/multi.vue';
import Single from '../containers/single.vue';
import Tabbed from '../containers/tabbed.vue';
import { reactive } from 'vue';

const registry: { [key: string]: any } = {
    multi: Multi,
    single: Single,
    tabbed: Tabbed,
};

interface ComponentProps {
    config: ListConfig,
    context: Context
}
const props = defineProps<ComponentProps>();

const state = reactive({
    container: props.config?.container || { type: 'multi' },
    frames: [] as ComponentContext
})

props.context.watch('$', Refresh);
Refresh();

function Refresh() {
    state.frames = Convert(props.context.data);
}

function Convert(data: any): ComponentContext {
    if (!data) {
        return [];
    }
    if (Array.isArray(data)) {
        return data.map((_, i) => ({ label: i.toString(), context: props.context, bind: i.toString(), config: props.config.section }));
    }
    if (typeof data == 'object') {
        return Object.keys(data).map((v) => ({ label: v, context: props.context, bind: v, config: props.config.section }));
    }
    return [];
}
</script>

<template>
    <component :is=registry[state.container.type] :config=state.container :frames=state.frames />
</template>

// src/lib/data-bound/layout/list.svelte
<script lang="ts">
    import type { Context } from '../lib/context';
    import type { FrameSet, ListConfig } from '../lib/types';
    import Multi from '../containers/multi.svelte';
    import Single from '../containers/single.svelte';
    import Tabbed from '../containers/tabbed.svelte';
    import Navigator from '../containers/navigator.svelte';

    export let context: Context;
    export let config: ListConfig;
    let frames: FrameSet = [];
    $: type = config?.container?.type || 'multi';

    context.watch('$', Refresh);
    Refresh();
    function Refresh() {
        frames = Convert(context.data);
    }

    function Convert(data: any): FrameSet {
        if (!data) {
            return [];
        }
        if (Array.isArray(data)) {
            return data.map((v, i) => ({ label: i.toString(), context, bind: i.toString(), config: config.section }));
        }
        if (typeof data == 'object') {
            return Object.keys(data).map((v) => ({ label: v, context, bind: v, config: config.section }));
        }
        return [];
    }
    const registry = {
        multi: Multi,
        single: Single,
        tabbed: Tabbed,
        navigator: Navigator,
    };
</script>

<svelte:component this={registry[type]} config={config.container} {frames} />
