// src/components/data-bound/layouts/output.vue
<script lang="ts" setup>
import type { OutputConfig } from "../services/types";
import type { Context } from "../services/context";
import Text from "../outputs/text.vue";

const registry: { [key: string]: typeof Text } = {
    text: Text,
};

interface ComponentProps {
    config: OutputConfig;
    context: Context;
}
const props = defineProps<ComponentProps>();

let value: any;
props.context.watch(props.config.bind, Refresh);
Refresh();

function Refresh() {
    value = props.context.get(props.config.bind);
}
</script>

<template>
    <component :is=registry[config.component.type] :value=value />
</template>

// src/lib/data-bound/layout/output.svelte
<script lang="ts">
    import type { InputConfig } from "../lib/types";
    import type { Context } from "../lib/context";
    import Text from "../outputs/text.svelte";

    export let config: InputConfig;
    export let context: Context;

    let value;
    context.watch(config.bind, Refresh);
    Refresh(null);

    function Refresh(e: any) {
        console.log(e);
        value = context.get(config.bind);
        value = value;
    }

    const registry = {
        text: Text,
    };
</script>

<svelte:component this={registry[config.component.type]} {value} />
