// src/lib/data-bound/containers/multi.svelte
<script lang="ts">
    import type { FrameSet } from '../lib/types';
    import Renderer from '../renderer.svelte';
    export let frames: FrameSet = [];
    export let config: any = {};
</script>

<div id={config.id} class={config.class} data-element="container" data-container="multi">
    {#each frames as frame}
        <Renderer config={frame.config} context={frame.context} bind={frame.bind} />
    {/each}
</div>

<style lang="scss">
</style>

// src/components/data-bound/containers/multi.vue
<script lang="ts" setup>
import type { ComponentContext, ContainerMultiConfig } from "../services/types";
import Renderer from "../Renderer.vue";
interface ComponentProps {
    frames: ComponentContext,
    config: ContainerMultiConfig
}
withDefaults(
    defineProps<ComponentProps>(),
    {
        frames: () => [],
        config: () => ({ type: 'multi' }),
    }
) as unknown as ComponentProps;

</script>

<template>
    <div :id=config.id :class=config.class data-element="container" data-container="multi">
        <Renderer v-for="frame in frames" :config=frame.config :context=frame.context :bind=frame.bind />
    </div>
</template>
