// src/lib/data-bound/renderer.svelte
<script lang="ts">
    import { beforeUpdate } from "svelte";
    import type { Context } from "./lib/context";
    import type {
        InputConfig,
        ListConfig,
        OutputConfig,
        SectionConfig,
    } from "./lib/types";

    import Input from "./layout/input.svelte";
    import Output from "./layout/output.svelte";
    import Section from "./layout/section.svelte";
    import List from "./layout/list.svelte";

    export let config:
        | SectionConfig
        | ListConfig
        | InputConfig
        | OutputConfig
        | any;
    export let context: Context;
    export let bind: string | undefined = undefined;
    let layout: { enabled: boolean; visible: boolean } = {
        visible: true,
    } as any;

    let localContext;
    const registry = {
        section: Section,
        input: Input,
        list: List,
        output: Output,
    };
    const directions = ["left-right", "right-left", "top-bottom", "bottom-top"];
    const wraps = ["nowrap", "wrap", "wrap-reverse"];
    $: direction =
        config.type == "input"
            ? ""
            : directions.includes(config.direction?.toLowerCase() as string)
              ? config.direction!.toLowerCase()
              : "left-right";
    $: wrap =
        config.type == "input"
            ? ""
            : wraps.includes(config.wrap?.toLowerCase() as string)
              ? config.wrap!.toLowerCase()
              : "nowrap";

    beforeUpdate(() => {
        if (typeof bind != "undefined" && config.type != "input") {
            localContext = context.fork(bind);
        } else if (config.bind && config.type != "input") {
            localContext = context.fork(config.bind);
        } else {
            localContext = context;
        }
    });
</script>

{#if layout.visible && config}
    <div
        id={config.id}
        class={config.class}
        data-element="layout"
        data-layout={config.type}
    >
        <div data-element="header">{config.header || ""}</div>
        <div data-element="content" data-direction={direction} data-wrap={wrap}>
            <svelte:component
                this={registry[config.type]}
                {config}
                context={localContext}
                {layout}
            />
        </div>

        <div data-element="footer">{config.footer || ""}</div>
    </div>
{/if}

<style lang="scss">
    [data-layout="input"] {
        [data-element="header"],
        [data-element="footer"] {
            &:empty {
                &:before {
                    content: "\00a0\00a0";
                }
            }
        }
    }
    [data-element="footer"] {
        font-size: 0.75em;
    }
</style>

// src/components/data-bound/Renderer.vue
<script lang="ts" setup>
import type { Context } from "./services/context";
import type {
  InputConfig,
  ListConfig,
  OutputConfig,
  SectionConfig,
} from "./services/types";

import Input from "./layouts/input.vue";
import Output from "./layouts/output.vue";
import Section from "./layouts/section.vue";
import List from "./layouts/list.vue";
import { computed } from "vue";

interface ComponentProps {
  context: Context;
  bind: string | undefined;
  config:
  | SectionConfig
  | ListConfig
  | InputConfig
  | OutputConfig
  | any
}
const props = withDefaults(
  defineProps<ComponentProps>(),
  {
    bind: undefined,
  }
) as unknown as ComponentProps;


let layouts: { enabled: boolean; visible: boolean } = {
  visible: true,
} as any;

let localContext = props.context;
const registry: { [key: string]: any } = {
  section: Section,
  input: Input,
  list: List,
  output: Output,
};
const directions = ["left-right", "right-left", "top-bottom", "bottom-top"];
const wraps = ["nowrap", "wrap", "wrap-reverse"];
const direction = computed(() =>
  props.config.type == "input"
    ? ""
    : directions.includes(props.config.direction?.toLowerCase() as string)
      ? props.config.direction!.toLowerCase()
      : "left-right");
const wrap = computed(() =>
  props.config.type == "input"
    ? ""
    : wraps.includes(props.config.wrap?.toLowerCase() as string)
      ? props.config.wrap!.toLowerCase()
      : "nowrap");

if (typeof props.bind != "undefined" && props.config.type != "input") {
  localContext = props.context.fork(props.bind);
} else if (props.config.bind && props.config.type != "input") {
  localContext = props.context.fork(props.config.bind);
} else {
  localContext = props.context;
}
</script>

<template>
  <div v-if="layouts.visible && config" :id=config.id :class=config.class :data-layout=config.type
    data-element="layout">
    <div data-element="header">{{ config.header || "" }}</div>
    <div data-element="content" :data-direction=direction :data-wrap=wrap>
      <component :is=registry[config.type] :config=config :context=localContext :layout=layouts />
    </div>

    <div data-element="footer">{{ config.footer || "" }}</div>
  </div>
</template>

<style lang="scss"></style>
