// src/lib/data-bound/layout/input.svelte
<script lang="ts">
    import type { InputConfig } from '../lib/types';
    import type { Context } from '../lib/context';
    import Text from '../inputs/text.svelte';
    import Checkbox from '../inputs/checkbox.svelte';

    export let config: InputConfig;
    export let context: Context;

    let value;
    context.watch(config.bind, Refresh);
    Refresh(null);

    function Refresh(e: any) {
        console.log(e);
        value = context.get(config.bind);
        value = value;
    }

    const registry = {
        text: Text,
        checkbox: Checkbox,
    };
    function onChange(value) {
        context.set(config.bind, value.detail);
    }
</script>

<svelte:component this={registry[config.component.type]} on:change={onChange} {value} />

// src/components/data-bound/layouts/input.vue
<script lang="ts" setup>
import type { InputConfig } from '../services/types';
import type { Context } from '../services/context';
import Text from '../inputs/text.vue';
import Checkbox from '../inputs/checkbox.vue';
import { ref } from 'vue';

interface ComponentProps {
    config: InputConfig,
    context: Context
}
const props = defineProps<ComponentProps>();

let value = ref();
props.context.watch(props.config.bind, Refresh);
Refresh();

function Refresh() {
    value.value = props.context.get(props.config.bind);
}

function onChange(value: any) {
    props.context.set(props.config.bind, value);
}

const registry: { [key: string]: typeof Text | typeof Checkbox } = {
    text: Text,
    checkbox: Checkbox,
}; 
</script>

<template>
    <component :is=registry[config.component.type] :value=value @change=onChange />
</template>
