// svelte/src/lib/data-bound/layout/section.svelte
<script lang="ts">
    import type { Context } from "../lib/context";
    import type { SectionConfig } from "../lib/types";
    import Renderer from "../renderer.svelte";

    export let config: SectionConfig;
    export let context: Context;
</script>

{#each config.sections as section}
    <Renderer config={section} {context} />
{/each}

// src/components/data-bound/layouts/section.vue
<script lang="ts" setup>
import type { Context } from "../services/context";
import type { SectionConfig } from "../services/types";
import Renderer from "../Renderer.vue";

interface ComponentProps {
    config: SectionConfig;
    context: Context;
}
defineProps<ComponentProps>();

</script>

<template>
    <Renderer v-for="section in config.sections" :config=section :context=context />
</template>
