// src/components/data-bound/layouts/controls/list.vue
<script lang="ts" setup>
import { reactive } from 'vue';
import { GetComponent } from '../../services/registry';
import type { ComponentContext, ConstrolStructureComponentProps } from '../../services/types';

const props = defineProps<ConstrolStructureComponentProps>();


const state = reactive({
    component: GetComponent('list', props.config?.component?.name || 'multi'),
    items: [] as ComponentContext
})

props.context.onDataChange(Refresh);
Refresh();

function Refresh() {
    state.items = Convert(props.context.data);
}

function Convert(data: any): ComponentContext {
    if (Array.isArray(data)) {
        return data.map((_, i) => ({ label: i.toString(), context: props.context, bind: i.toString() }));
    }
    if (typeof data == 'object') {
        return Object.keys(data).map((v) => ({ label: v, context: props.context, bind: v }));
    }
    return [];
}

</script>

<template>
    <component :is="state.component" :config="props.config" :items="state.items" />
</template>

// svelte/src/lib/data-bound/layout/list.svelte
<script lang="ts">
    import type { Context } from '../lib/context';
    import type { ComponentContext, ListConfig } from '../lib/types';
    import Multi from '../containers/multi.svelte';
    import Single from '../containers/single.svelte';
    import Tabbed from '../containers/tabbed.svelte';

    export let context: Context;
    export let config: ListConfig;
    let frames: ComponentContext = [];
    $: configContainer = config?.container || { type: 'multi' };

    context.watch('$', Refresh);
    Refresh();
    function Refresh() {
        frames = Convert(context.data);
    }

    function Convert(data: any): ComponentContext {
        if (!data) {
            return [];
        }
        if (Array.isArray(data)) {
            return data.map((v, i) => ({ label: i.toString(), context, bind: i.toString(), config: config.section }));
        }
        if (typeof data == 'object') {
            return Object.keys(data).map((v) => ({ label: v, context, bind: v, config: config.section }));
        }
        return [];
    }
    const registry = {
        multi: Multi,
        single: Single,
        tabbed: Tabbed,
    };
</script>

<svelte:component this={registry[configContainer.type]} config={configContainer} {frames} />
