// svelte/src/lib/data-bound/inputs/code.svelte
<script context="module" lang="ts">
    import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
    import jsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker';
    import cssWorker from 'monaco-editor/esm/vs/language/css/css.worker?worker';
    import htmlWorker from 'monaco-editor/esm/vs/language/html/html.worker?worker';
    import tsWorker from 'monaco-editor/esm/vs/language/typescript/ts.worker?worker';
</script>

<script lang="ts">
    import type { editor } from 'monaco-editor';
    import { onMount, onDestroy, createEventDispatcher } from 'svelte';

    export let value = '';
    export let language = 'json';
    export let minHeight = 200;
    export let maxHeight = 0;
    export let minWidth = 600;
    export let maxWidth = 0;
    export let theme = 'vs-light';
    export let width: 'fill' | 'auto' = 'fill';
    export let height: 'fill' | 'auto' = 'fill';
    export let settings: editor.IStandaloneEditorConstructionOptions = {};

    let container: HTMLDivElement;
    const dispatch = createEventDispatcher();
    let codeEditor: editor.IStandaloneCodeEditor;
    let Monaco;
    $: {
        if (codeEditor && value != codeEditor.getValue()) {
            codeEditor.setValue(value);
            resize();
        }

        if (codeEditor) {
            Monaco.editor.setTheme(theme);
        }
    }

    onMount(async () => {
        Monaco = await import('monaco-editor');

        (window as any).MonacoEnvironment = {
            getWorker(_, label) {
                if (label === 'json') {
                    return new jsonWorker();
                }
                if (label === 'css' || label === 'scss' || label === 'less') {
                    return new cssWorker();
                }
                if (label === 'html' || label === 'handlebars' || label === 'razor') {
                    return new htmlWorker();
                }
                if (label === 'typescript' || label === 'javascript') {
                    return new tsWorker();
                }
                return new editorWorker();
            },
        };

        codeEditor = Monaco.editor.create(container, {
            value,
            language,
            theme,
            scrollBeyondLastLine: false,
            automaticLayout: true,
            ...settings,
        });

        resize();
        codeEditor?.getModel()?.onDidChangeContent(() => {
            value = codeEditor.getValue();
            resize();
            dispatch('edit', value);
        });
        dispatch('load', {
            resize,
        });
    });

    onDestroy(() => {
        if (codeEditor) {
            codeEditor.dispose();
            const model = codeEditor.getModel();
            if (model) model.dispose();
        }
    });

    function resize() {
        container.style.display = 'block';
        container.style.width = '100%';
        container.style.height = '100%';

        let targetWidth = container.offsetWidth;
        let targetHeight = container.offsetHeight;

        if (width == 'auto') {
            targetWidth = codeEditor.getContentWidth();
        }

        if (height == 'auto') {
            targetHeight = codeEditor.getContentHeight();
        }

        const newWidth = Math.max(minWidth, Math.min(maxWidth || targetWidth, targetWidth));
        const newHeight = Math.max(minHeight, Math.min(maxHeight || targetHeight, targetHeight));

        codeEditor.layout({ width: newWidth, height: newHeight });
        container.style.height = `${newHeight}px`;
        container.style.width = `${newWidth}px`;
    }
</script>

<div bind:this={container} class="editor" />

<style>
    .editor {
        height: 100%;
        width: 100%;
        position: relative;
    }
</style>

// src/components/Code.vue
<script lang="ts" setup>
import { cssWorker, htmlWorker, tsWorker, editorWorker, jsonWorker } from '../services/workers';
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { editor } from 'monaco-editor';

interface ComponentProps {
    value: string;
    language: string;
    minHeight: number;
    maxHeight: number;
    minWidth: number;
    maxWidth: number;
    theme: string;
    width: 'fill' | 'auto';
    height: 'fill' | 'auto';
    settings: editor.IStandaloneEditorConstructionOptions;
}
const props = withDefaults(
    defineProps<ComponentProps>(),
    {
        value: '',
        language: 'json',
        minHeight: 200,
        maxHeight: 0,
        minWidth: 600,
        maxWidth: 0,
        theme: 'vs-light',
        width: 'fill',
        height: 'fill',
        settings: {},
    } as any
) as unknown as ComponentProps;
const emit = defineEmits<{ edit: [string], load: [{ resize: () => void }] }>()
const container = ref<HTMLDivElement>();
let codeEditor: editor.IStandaloneCodeEditor;
// let Monaco: any;

watch(props, () => {
    if (codeEditor && props.value != codeEditor.getValue()) {
        codeEditor.setValue(props.value);
        resize();
    }
    if (codeEditor && editor) {
        editor.setTheme(props.theme);
    }
})

onMounted(() => {
    console.log(container.value)
    if (container.value) {
        // Monaco = await import('monaco-editor');
        if (!window.MonacoEnvironment) {
            (window as any).MonacoEnvironment = {
                getWorker(_: any, label: any) {
                    if (label === 'json') {
                        return new jsonWorker();
                    }
                    if (label === 'css' || label === 'scss' || label === 'less') {
                        return new cssWorker();
                    }
                    if (label === 'html' || label === 'handlebars' || label === 'razor') {
                        return new htmlWorker();
                    }
                    if (label === 'typescript' || label === 'javascript') {
                        return new tsWorker();
                    }
                    return new editorWorker();
                },
            }
        }

        codeEditor = editor.create(container.value, {
            value: props.value,
            language: props.language,
            theme: props.theme,
            scrollBeyondLastLine: false,
            automaticLayout: true,
            ...props.settings,
        });

        resize();
        codeEditor?.getModel()?.onDidChangeContent(() => {
            const val = codeEditor?.getValue() as string;
            props.value = val;
            resize();
            emit('edit', val);
        });
        emit('load', { resize });
    }
});

onUnmounted(() => {
    if (codeEditor) {
        codeEditor.dispose();
        const model = codeEditor.getModel();
        if (model)
            model.dispose();
    }
});

function resize() {
    if (container.value && codeEditor) {
        container.value.style.display = 'block';
        container.value.style.width = '100%';
        container.value.style.height = '100%';

        let targetWidth = container.value.offsetWidth;
        let targetHeight = container.value.offsetHeight;

        if (props.width == 'auto') {
            targetWidth = codeEditor.getContentWidth();
        }

        if (props.height == 'auto') {
            targetHeight = codeEditor.getContentHeight();
        }

        const newWidth = Math.max(props.minWidth, Math.min(props.maxWidth || targetWidth, targetWidth));
        const newHeight = Math.max(props.minHeight, Math.min(props.maxHeight || targetHeight, targetHeight));

        codeEditor.layout({ width: newWidth, height: newHeight });
        container.value.style.height = `${newHeight}px`;
        container.value.style.width = `${newWidth}px`;
    }
}
</script>

<template>
    <div ref=container class="editor" />
</template>

<style lang="scss">
.editor {
    height: 100%;
    width: 100%;
    position: relative;
}
</style>
