// src/lib/data-bound/layout/input.svelte
<script lang="ts">
    import type { InputConfig } from '../lib/types';
    import type { Context } from '../lib/context';
    import Text from '../inputs/text.svelte';
    import Checkbox from '../inputs/checkbox.svelte';

    export let config: InputConfig;
    export let context: Context;

    let value;
    context.watch(config.bind, Refresh);
    Refresh(null);

    function Refresh(e: any) {
        console.log(e);
        value = context.get(config.bind);
        value = value;
    }

    const registry = {
        text: Text,
        checkbox: Checkbox,
    };
    function onChange(value) {
        context.set(config.bind, value.detail);
    }
</script>

<svelte:component this={registry[config.component.type]} on:change={onChange} {value} />

// src/components/data-bound/layouts/controls/input.vue
<script lang="ts" setup>
import { reactive, ref, watch } from 'vue';
import type { ConstrolStructureComponentProps } from '../../services/types';
import { GetComponent } from '../../services/registry';

const props = defineProps<ConstrolStructureComponentProps>();

let value = ref();
watch(props, Refresh);
Refresh();

function Refresh() {
    value.value = props.context.data;
}

function onChange(value: any) {
    props.context.data = value;
}

const state = reactive({
    component: GetComponent('input', props.config?.component || 'text'),
})
</script>

<template>
    <component :is="state.component" :config="config" :value="value" @change="onChange" />
</template>
