// svelte/src/lib/data-bound/layout/workspace.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import type { ComponentContext, WorkspaceConfig } from "../lib/types";
    import Multi from "../containers/multi.svelte";
    import Single from "../containers/single.svelte";
    import Tabbed from "../containers/tabbed.svelte";
    import type { Context } from "../lib/context";

    export let config: WorkspaceConfig;
    export let context: Context;
    let frames: ComponentContext = [];
    $: type = "single";

    onMount(() => {
        // OpenFrame('', config.initial, data);
    });

    export function OpenFrame(label: string, layout: string, bind: string) {
        const frame = {
            label,
            context,
            bind,
            config: context.application.layout(layout),
        };
        frames.push(frame);
        frames = frames;
        return frame;
    }
    export function CloseFrame(frame: (typeof frames)[number]) {
        const i = frames.indexOf(frame);
        if (i >= 0) {
            frames.splice(i, 1);
        }
    }

    const registry = {
        multi: Multi,
        single: Single,
        tabbed: Tabbed,
    };
</script>

<svelte:component this={registry[type]} config={null} {frames} />

// src/components/data-bound/layouts/controls/workspace.vue
<script lang="ts" setup>
import type { ComponentContext, ConstrolStructureComponentProps } from "../../services/types";
import Multi from "../lists/multi.vue";
import Single from "../lists/single.vue";
import Tabbed from "../lists/tabs.vue";

const props = defineProps<ConstrolStructureComponentProps>();

let items: ComponentContext = [];
let type = "single";



export function OpenFrame(label: string, layout: string, bind: string) {
    const item = {
        label,
        context: props.context,
        bind,
        layout: props.context.application.layout(layout),
    };
    items.push(item);
    return item;
}
export function CloseFrame(item: (typeof items)[number]) {
    const i = items.indexOf(item);
    if (i >= 0) {
        items.splice(i, 1);
    }
}

const registry: { [key: string]: any } = {
    single: Single,
    multi: Multi,
    tabs: Tabbed,
};
</script>

<template>
    <component :is=registry[type] :config=null :items=items />
</template>
