// src/components/data-bound/layouts/lists/single.vue
<script lang="ts" setup>
import type { ListComponentProps, ListSingleConfig } from "../../services/types";
import Renderer from "../../Renderer.vue";
import { computed } from "vue";
const props = defineProps<ListComponentProps<ListSingleConfig>>();
let item = computed(() => props.items[props.items.length - 1]);

</script>

<template>
    <div data-control="list" data-component="single">
        <Renderer v-if="item" :config="props.config.layout" :context="item.context" :bind="item.bind" />
    </div>
</template>

// src/lib/data-bound/containers/single.svelte
<script lang="ts">
    import type { FrameSet } from '../lib/types';
    import Renderer from '../renderer.svelte';

    export let frames: FrameSet = [];
    export let config: any = {};
    $: frame = frames[frames.length - 1];
</script>

<div id={config.id} class={config.class} data-element="container" data-container="single">
    {#if frame}
        <Renderer config={frame.config} context={frame.context} bind={frame.bind} />
    {/if}
</div>

<style lang="scss">
</style>
